apiVersion: v1
kind: ConfigMap
metadata:
  name: users-config
  namespace: fcg
data:
  RabbitMq__Host: "rabbitmq"
  JwtSettings__Issuer: "FiapCloudGames"
  JwtSettings__Audience: "FiapCloudGames.Client"
