apiVersion: v1
kind: Secret
metadata:
  name: users-secret
  namespace: fcg
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=users-db;Database=users;User Id=sa;Password=Your_strong_Pass1;TrustServerCertificate=true"
  JwtSettings__SecretKey: "fcg-fase2-shared-secret-key-please-change-32+chars"
  RabbitMq__User: "guest"
  RabbitMq__Pass: "guest"
